spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finisher_batch1
    username: root
    password: ramkumar
    type: org.apache.commons.dbcp2.BasicDataSource